[package]
name = "mcaptcha-cli"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
pow_sha256 = { version = "0.2.1", git = "https://github.com/mCaptcha/pow_sha256" }
clap = "2.33"
